FROM node:20-alpine3.19

# Optional: Setze Version
ARG NEXT_PUBLIC_VERSION
ENV NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION

# Installiere nur, was nötig ist
RUN apk add --no-cache g++ make py3-pip bash

# Installiere pnpm
RUN npm install -g pnpm@10.6.1

WORKDIR /app

# Kopiere Projekt
COPY . /app

# Installiere Abhängigkeiten
RUN pnpm install

# Baue das Projekt
RUN pnpm run build

# Setze den Port, auf dem NestJS läuft
EXPOSE 5000

# Starte NUR das Backend
CMD ["pnpm", "--filter", "postiz-backend", "start"]
